# Generated by Django 2.0.5 on 2018-08-10 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Titles',
            fields=[
                ('article', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='filesgetter.Titles')),
                ('title', models.CharField(max_length=200)),
                ('price', models.FloatField(max_length=10)),
                ('gross_weight', models.IntegerField(max_length=10)),
                ('creation_date', models.DateField()),
                ('update_field', models.DateField()),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
