# Generated by Django 2.0.5 on 2018-08-10 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesgetter', '0002_auto_20180810_0449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titles',
            name='title',
        ),
        migrations.AlterField(
            model_name='titles',
            name='article',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
