# Generated by Django 2.0.5 on 2018-08-10 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesgetter', '0003_auto_20180810_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='cost_price',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='article',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Titles',
        ),
    ]
