# Generated by Django 2.0.5 on 2018-08-10 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filesgetter', '0004_auto_20180810_0635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameters',
            old_name='update_field',
            new_name='update_date',
        ),
    ]
