# Generated by Django 2.0.5 on 2018-08-10 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesgetter', '0005_auto_20180810_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameters',
            name='category',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='price',
            field=models.FloatField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='title',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
