# Generated by Django 2.0.5 on 2018-08-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesgetter', '0006_auto_20180810_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameters',
            name='cost_price',
            field=models.FloatField(default=''),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='price',
            field=models.FloatField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
