# Generated by Django 2.0.5 on 2018-08-10 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesgetter', '0008_auto_20180810_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameters',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
